# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifprcursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='q9',
        ),
        migrations.AddField(
            model_name='resposta',
            name='respostas',
            field=models.CommaSeparatedIntegerField(max_length=255, null=True),
        ),
    ]
