# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifprcursos', '0002_auto_20171125_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='curso',
            field=models.IntegerField(null=True, verbose_name='curso'),
        ),
    ]
